import type { ScoreReport } from "../core/types.js";

export type SkillFormat = "agents" | "claude" | "cursor" | "copilot";

/** Default output filename for each supported format. */
export const SKILL_FILENAMES: Record<SkillFormat, string> = {
  agents: "AGENTS.md",
  claude: "CLAUDE.md",
  cursor: ".cursorrules",
  copilot: ".github/copilot-instructions.md",
};

/** Build the shared set of actionable rules from the report. */
function buildRules(report: ScoreReport): string[] {
  const d = report.detection;
  const f = report.folder;
  const rules: string[] = [];

  rules.push(
    `This is a **${d.projectType}** project (primary language: ${d.primaryLanguage}` +
      (d.frameworks.length ? `, using ${d.frameworks.join(", ")}` : "") +
      `). Follow the conventions below when reading, writing, or refactoring code.`,
  );

  rules.push(
    `**Architecture:** Target a **${f.recommended}** structure. ${f.rationale}`,
  );

  rules.push(
    `**Folder structure:** Place new code according to this layout:\n\n\`\`\`\n${f.proposedTree}\n\`\`\``,
  );

  // Encode the most impactful, still-open recommendations as guardrails.
  const open = report.recommendations.slice(0, 10);
  if (open.length) {
    const items = open.map((r) => `- ${r.fix}`).join("\n");
    rules.push(`**Apply these standards (the project currently falls short on them):**\n${items}`);
  }

  // Category-level do's derived from the rubric, tailored by what's weak.
  const weak = report.categories.filter((c) => c.applicable && c.score < 80);
  if (weak.length) {
    const byCat = weak
      .map((c) => `- **${c.title}**: ${c.findings.map((fd) => fd.fix).join(" ")}`)
      .join("\n");
    rules.push(`**Per-category guidance:**\n${byCat}`);
  }

  rules.push(
    `**General system-design rules:**\n` +
      `- Keep entry points thin; put business logic in dedicated modules.\n` +
      `- Externalize configuration via environment variables; never hardcode secrets or endpoints.\n` +
      `- Handle errors explicitly — never swallow them in empty catch blocks.\n` +
      `- Add or update tests alongside code changes; cover core logic and IO boundaries.\n` +
      `- Use structured logging; add timeouts/retries around network calls in services.\n` +
      `- Avoid circular dependencies and god-modules; depend on abstractions, not concretes.`,
  );

  return rules;
}

/** Generate an AI-assistant guidance file in the requested format. */
export function generateSkill(report: ScoreReport, format: SkillFormat): string {
  const rules = buildRules(report);
  const body = rules.join("\n\n");
  const stamp = `<!-- Generated by arch-score v${report.version} on ${report.generatedAt.slice(0, 10)}. Re-run \`archscore --emit-skill\` to refresh. -->`;

  switch (format) {
    case "cursor":
      // .cursorrules is plain text rules.
      return [
        `# Project coding rules (system design)`,
        ``,
        rules.join("\n\n"),
        ``,
        stamp,
      ].join("\n");
    case "copilot":
      return [
        `# Copilot Instructions`,
        ``,
        `These instructions guide GitHub Copilot to follow this project's system-design standards.`,
        ``,
        body,
        ``,
        stamp,
      ].join("\n");
    case "claude":
      return [
        `# CLAUDE.md`,
        ``,
        `Guidance for Claude / Claude Code when working in this repository.`,
        ``,
        body,
        ``,
        stamp,
      ].join("\n");
    case "agents":
    default:
      return [
        `# AGENTS.md`,
        ``,
        `Instructions for AI coding agents working in this repository. Follow these system-design conventions.`,
        ``,
        body,
        ``,
        stamp,
      ].join("\n");
  }
}
