import type { ScoreReport } from "../core/types.js";
import { CATEGORY_TITLES } from "../core/constants.js";

/** Generate a human-readable SYSTEM_DESIGN.md playbook from a report. */
export function generateSystemDesign(report: ScoreReport): string {
  const d = report.detection;
  const f = report.folder;
  const lines: string[] = [];
  const p = (s = "") => lines.push(s);

  p(`# System Design Playbook`);
  p();
  p(`> Generated by [arch-score](https://www.npmjs.com/package/arch-score) v${report.version} on ${report.generatedAt.slice(0, 10)}.`);
  p(`> A heuristic advisor — treat these as prioritized guidance, not hard rules.`);
  p();
  p(`**Project type:** ${d.projectType}  ·  **Primary language:** ${d.primaryLanguage}` +
    (d.frameworks.length ? `  ·  **Frameworks:** ${d.frameworks.join(", ")}` : ""));
  p(`**Overall score:** ${report.overall}/100 (grade ${report.grade})  ·  **Analysis tier:** ${report.tierUsed}`);
  p();

  p(`## Category scores`);
  p();
  p(`| Category | Score | Weight | Tier |`);
  p(`| --- | ---: | ---: | --- |`);
  for (const c of report.categories) {
    if (!c.applicable) {
      p(`| ${c.title} | n/a | — | ${c.tier} (re-weighted out) |`);
    } else {
      p(`| ${c.title} | ${c.score}/100 | ${c.weight.toFixed(0)} | ${c.tier} |`);
    }
  }
  p();

  p(`## Recommended folder structure`);
  p();
  p(`Current structure reads as **${f.current}**; the recommended target for a ${f.projectType} project is **${f.recommended}**.`);
  p();
  p(`> ${f.rationale}`);
  p();
  p("```");
  p(f.proposedTree);
  p("```");
  p();
  if (f.gaps.length) {
    p(`### Gaps vs. recommended layout`);
    p();
    for (const g of f.gaps) p(`- ${g}`);
    p();
  }

  p(`## Prioritized fixes`);
  p();
  if (report.recommendations.length === 0) {
    p(`No significant issues detected. 🎉`);
  } else {
    report.recommendations.forEach((r, i) => {
      p(`${i + 1}. **${r.message}**`);
      p(`   - Fix: ${r.fix}`);
      if (r.refs && r.refs.length) p(`   - Refs: ${r.refs.map((x) => `\`${x}\``).join(", ")}`);
    });
  }
  p();

  p(`## Standards by category`);
  p();
  for (const c of report.categories) {
    p(`### ${CATEGORY_TITLES[c.key]}`);
    if (!c.applicable) {
      p(`_Not assessed (re-weighted out): ${(c.notes ?? []).join(" ")}_`);
      p();
      continue;
    }
    p(`Score: ${c.score}/100.`);
    if (c.findings.length === 0) {
      p(`- ✅ No issues found.`);
    } else {
      for (const fd of c.findings) {
        p(`- **${fd.message}** — ${fd.fix}`);
      }
    }
    p();
  }

  if (report.deep) {
    const dm = report.deep;
    p(`## Dependency analysis (deep tier — ${dm.language})`);
    p();
    p(`- Modules analyzed: ${dm.moduleCount}`);
    p(`- Circular dependency cycles: ${dm.cycles.length}`);
    p(`- Max dependency depth: ${dm.maxDepth}`);
    if (dm.cycles.length) {
      p();
      p(`Cycles:`);
      for (const cyc of dm.cycles.slice(0, 10)) p(`- \`${cyc.join(" → ")}\``);
    }
    p();
  }

  p(`---`);
  p(`_Re-run \`archscore .\` after addressing fixes to track progress._`);
  p();
  return lines.join("\n");
}
