import type { ScoreReport } from "../core/types.js";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function band(score: number): string {
  if (score >= 80) return "good";
  if (score >= 60) return "ok";
  return "bad";
}

/** Render a self-contained HTML report (no external assets). */
export function renderHtml(report: ScoreReport): string {
  const cats = report.categories
    .map((c) => {
      if (!c.applicable) {
        return `<tr class="na"><td>${esc(c.title)}</td><td colspan="2">n/a — re-weighted out (${esc(c.tier)})</td></tr>`;
      }
      return `<tr>
        <td>${esc(c.title)}</td>
        <td class="num ${band(c.score)}">${c.score}</td>
        <td><div class="track"><div class="fill ${band(c.score)}" style="width:${c.score}%"></div></div><span class="w">w${c.weight.toFixed(0)} · ${esc(c.tier)}</span></td>
      </tr>`;
    })
    .join("\n");

  const recs = report.recommendations
    .slice(0, 15)
    .map(
      (r) =>
        `<li><div class="rec-msg">${esc(r.message)}</div><div class="rec-fix">${esc(r.fix)}</div>${
          r.refs && r.refs.length
            ? `<div class="rec-refs">${esc(r.refs.slice(0, 4).join(", "))}</div>`
            : ""
        }</li>`,
    )
    .join("\n");

  const f = report.folder;
  const gaps = f.gaps.map((g) => `<li>${esc(g)}</li>`).join("\n");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>arch-score report — ${esc(report.detection.projectType)}</title>
<style>
  :root{--good:#2ea043;--ok:#d29922;--bad:#cf222e;--bg:#0d1117;--panel:#161b22;--fg:#e6edf3;--muted:#8b949e;--border:#30363d}
  *{box-sizing:border-box}
  body{margin:0;font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:var(--bg);color:var(--fg)}
  .wrap{max-width:900px;margin:0 auto;padding:40px 24px}
  h1{font-size:20px;margin:0 0 4px}.sub{color:var(--muted);margin-bottom:28px}
  .overall{display:flex;align-items:center;gap:24px;background:var(--panel);border:1px solid var(--border);border-radius:12px;padding:24px;margin-bottom:28px}
  .score{font-size:56px;font-weight:700;line-height:1}
  .grade{font-size:24px;color:var(--muted)}
  .good{color:var(--good)}.ok{color:var(--ok)}.bad{color:var(--bad)}
  table{width:100%;border-collapse:collapse;background:var(--panel);border:1px solid var(--border);border-radius:12px;overflow:hidden}
  td{padding:10px 16px;border-top:1px solid var(--border)}
  tr:first-child td{border-top:none}
  .num{font-weight:700;text-align:right;width:48px}
  .na{color:var(--muted)}
  .track{display:inline-block;width:160px;height:8px;background:#21262d;border-radius:4px;overflow:hidden;vertical-align:middle}
  .fill{height:100%}.fill.good{background:var(--good)}.fill.ok{background:var(--ok)}.fill.bad{background:var(--bad)}
  .w{color:var(--muted);font-size:12px;margin-left:10px}
  h2{font-size:15px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);margin:32px 0 12px}
  ol,ul{padding-left:20px}
  .rec-msg{font-weight:600}.rec-fix{color:var(--muted)}.rec-refs{color:var(--muted);font-size:12px;font-family:ui-monospace,monospace}
  li{margin-bottom:12px}
  pre{background:var(--panel);border:1px solid var(--border);border-radius:12px;padding:16px;overflow:auto;font-family:ui-monospace,SFMono-Regular,monospace;font-size:13px}
  .chip{display:inline-block;background:var(--panel);border:1px solid var(--border);border-radius:999px;padding:2px 10px;font-size:12px;color:var(--muted);margin-right:6px}
  footer{color:var(--muted);font-size:12px;margin-top:40px;border-top:1px solid var(--border);padding-top:16px}
</style></head>
<body><div class="wrap">
  <h1>arch-score report</h1>
  <div class="sub">
    <span class="chip">${esc(report.detection.projectType)}</span>
    <span class="chip">${esc(report.detection.primaryLanguage)}</span>
    ${report.detection.frameworks.map((fw) => `<span class="chip">${esc(fw)}</span>`).join("")}
    <span class="chip">${esc(report.tierUsed)} tier</span>
  </div>

  <div class="overall">
    <div><div class="score ${band(report.overall)}">${report.overall}</div></div>
    <div>
      <div class="grade ${band(report.overall)}">Grade ${esc(report.grade)}</div>
      <div class="sub" style="margin:0">Weighted across ${report.categories.filter((c) => c.applicable).length} categories</div>
    </div>
  </div>

  <h2>Category scores</h2>
  <table>${cats}</table>

  <h2>Top recommendations</h2>
  <ol>${recs || "<li>No issues found.</li>"}</ol>

  <h2>Folder structure — ${esc(f.current)} → ${esc(f.recommended)}</h2>
  <p>${esc(f.rationale)}</p>
  ${gaps ? `<ul>${gaps}</ul>` : ""}
  <pre>${esc(f.proposedTree)}</pre>

  <footer>Generated by arch-score v${esc(report.version)} · ${esc(report.generatedAt)}</footer>
</div></body></html>`;
}
